kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-lifesense-qa2-redis-app-3
  namespace: base
  labels:
    type: redis-nfs-claim
    app: redis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      path: nfsshare4
      app: redis
      podindex: "3"
