apiVersion: v1
kind: Service
metadata:
  name: lifesense-qa-redis-service
  namespace: base
  labels:
    app: redis
spec:
  ports:
  - name: redis-port
    port: 6379
  clusterIP: None
  selector:
    app: redis
    appCluster: redis-cluster
