apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol5
  namespace: base
  labels:
    path: nfsshare5
    type: redis-nfs
    app: redis
    podindex: "4"
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.9.34.61
    path: "/data/nfs/qa2/n5"
