apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol2
  namespace: base
  labels:
    path: nfsshare2
    type: redis-nfs
    app: redis
    podindex: "1"
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.9.34.61
    path: "/data/nfs/qa/n2"
