apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol5
  labels:
    path: nfsshare5
    type: redis-nfs
    app: redis
    podindex: "4"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.9.34.61
    path: "/data/nfs/n5"