apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol1
  namespace: base
  labels:
    path: nfsshare1
    type: redis-nfs
    app: redis
    podindex: "0"
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.9.34.61
    path: "/data/nfs/qa/n1"
